"""
Captioning provider — runs VLM inference on images.

Currently ships with a mock implementation that returns fake captions
so the full pipeline (Node → sidecar → localStorage → Redux → UI) can be
validated before wiring up llama-cpp-python.

Swap MockCaptioningProvider for LlamaCppCaptioningProvider when ready.
"""

from __future__ import annotations

import asyncio
import os
from abc import ABC, abstractmethod


class CaptioningProvider(ABC):
    """Abstract base for captioning backends."""

    @abstractmethod
    async def caption_image(
        self,
        image_path: str,
        model_path: str,
        prompt: str,
        max_tokens: int = 512,
        temperature: float = 0.7,
    ) -> str:
        """Return a natural-language caption for the image."""

    @abstractmethod
    async def unload(self) -> None:
        """Release any cached model resources (GPU memory, etc.)."""


class MockCaptioningProvider(CaptioningProvider):
    """
    Mock provider that returns deterministic fake captions.

    Used to validate the end-to-end pipeline without needing a real VLM.
    Simulates ~300ms of inference per image so batch progress feels real.
    """

    def __init__(self) -> None:
        self._loaded_model: str | None = None

    async def caption_image(
        self,
        image_path: str,
        model_path: str,
        prompt: str,
        max_tokens: int = 512,
        temperature: float = 0.7,
    ) -> str:
        # Simulate model loading (first call only)
        if self._loaded_model != model_path:
            await asyncio.sleep(0.5)
            self._loaded_model = model_path

        # Simulate per-image inference latency
        await asyncio.sleep(0.3)

        filename = os.path.basename(image_path)
        return (
            f"A detailed descriptive caption for {filename}. "
            f"This is a mock response generated by the sidecar for testing. "
            f"Prompt was: {prompt[:80]}"
        )

    async def unload(self) -> None:
        self._loaded_model = None


# Module-level singleton — one provider instance per sidecar process
_provider: CaptioningProvider | None = None


def get_provider() -> CaptioningProvider:
    """Get the current captioning provider (lazily instantiated)."""
    global _provider
    if _provider is None:
        _provider = MockCaptioningProvider()
    return _provider


async def unload_provider() -> None:
    """Release the current provider's model resources."""
    global _provider
    if _provider is not None:
        await _provider.unload()
