"""
Captioning provider — runs VLM inference on images.

Backends:
- MockCaptioningProvider: fake captions with simulated latency, for pipeline testing
- LlamaCppCaptioningProvider: GGUF inference via llama-cpp-python (CPU, Linux CUDA)
- TransformersCaptioningProvider: safetensors fp16 via PyTorch CUDA (Windows GPU path)

The active provider is chosen by get_provider(runtime). Each runtime has its
own lazy-loaded singleton, so loading one doesn't touch the other. This lets
a user keep a GGUF model loaded for CPU captioning while also having the GPU
transformers model swappable in without fighting over the cache.

When a requested runtime isn't installed, the mock provider is returned so
the pipeline stays testable — errors surface the missing extra.
"""

from __future__ import annotations

import asyncio
import os
import sys
from abc import ABC, abstractmethod
from typing import Callable, Literal, Optional

VlmRuntime = Literal["llama-cpp", "transformers"]

# Type alias for the cooperative cancellation callback. The batch manager
# passes a closure that reads its own `cancel_requested` flag; the provider
# polls it during inference and raises CaptionCancelled when it flips true.
CancelCheck = Callable[[], bool]


class CaptionCancelled(Exception):
    """Raised by a provider when inference is aborted via cancel_check."""


class CaptioningProvider(ABC):
    """Abstract base for captioning backends."""

    @abstractmethod
    async def caption_image(
        self,
        image_path: str,
        model_path: str,
        prompt: str,
        max_tokens: int = 512,
        temperature: float = 0.7,
        cancel_check: Optional[CancelCheck] = None,
    ) -> str:
        """Return a natural-language caption for the image."""

    @abstractmethod
    async def unload(self) -> None:
        """Release any cached model resources (GPU memory, etc.)."""


class MockCaptioningProvider(CaptioningProvider):
    """
    Mock provider that returns deterministic fake captions.

    Used to validate the end-to-end pipeline without needing a real VLM.
    Simulates ~300ms of inference per image so batch progress feels real.
    """

    def __init__(self) -> None:
        self._loaded_model: str | None = None

    async def caption_image(
        self,
        image_path: str,
        model_path: str,
        prompt: str,
        max_tokens: int = 512,
        temperature: float = 0.7,
        cancel_check: Optional[CancelCheck] = None,
    ) -> str:
        # Simulate model loading (first call only)
        if self._loaded_model != model_path:
            await asyncio.sleep(0.5)
            self._loaded_model = model_path

        # Simulate per-image inference latency, checking for cancellation
        for _ in range(3):
            if cancel_check and cancel_check():
                raise CaptionCancelled("cancelled during mock inference")
            await asyncio.sleep(0.1)

        filename = os.path.basename(image_path)
        return (
            f"A detailed descriptive caption for {filename}. "
            f"This is a mock response generated by the sidecar for testing. "
            f"Prompt was: {prompt[:80]}"
        )

    async def unload(self) -> None:
        self._loaded_model = None


# One lazily-instantiated singleton per runtime. Loading the transformers
# provider does not touch the llama-cpp one, and vice versa.
_providers: dict[str, CaptioningProvider] = {}


def _instantiate(runtime: VlmRuntime) -> CaptioningProvider:
    """Build a provider for the requested runtime, falling back to mock."""
    if runtime == "transformers":
        try:
            from captioning.transformers_provider import (
                TransformersCaptioningProvider,
            )

            print("[sidecar] Captioning: using TransformersCaptioningProvider")
            return TransformersCaptioningProvider()
        except ImportError as err:
            print(
                f"[sidecar] Captioning: transformers unavailable ({err}), "
                "falling back to mock. Install with: uv sync --extra gpu",
                file=sys.stderr,
            )
            return MockCaptioningProvider()

    if runtime == "llama-cpp":
        try:
            from captioning.llama_cpp_provider import LlamaCppCaptioningProvider

            print("[sidecar] Captioning: using LlamaCppCaptioningProvider")
            return LlamaCppCaptioningProvider()
        except ImportError as err:
            print(
                f"[sidecar] Captioning: llama-cpp-python unavailable ({err}), "
                "falling back to mock. Install with: uv sync --extra vlm",
                file=sys.stderr,
            )
            return MockCaptioningProvider()

    raise ValueError(f"Unknown VLM runtime: {runtime}")


def get_provider(runtime: VlmRuntime = "llama-cpp") -> CaptioningProvider:
    """
    Get the captioning provider for the requested runtime.

    Providers are cached per-runtime so repeat calls don't reload the model.
    The default is 'llama-cpp' for backwards compatibility with callers that
    predate the runtime dispatch change.
    """
    existing = _providers.get(runtime)
    if existing is not None:
        return existing
    provider = _instantiate(runtime)
    _providers[runtime] = provider
    return provider


async def unload_provider(runtime: Optional[VlmRuntime] = None) -> None:
    """
    Release model resources. If `runtime` is given, unload that runtime only.
    Otherwise unload all cached providers.
    """
    targets = [runtime] if runtime is not None else list(_providers.keys())
    for key in targets:
        provider = _providers.get(key)
        if provider is not None:
            await provider.unload()
