"""
Captioning provider — runs VLM inference on images.

Backends:
- MockCaptioningProvider: fake captions with simulated latency, for pipeline testing
- LlamaCppCaptioningProvider: real inference via llama-cpp-python (CPU or Linux CUDA)

The active provider is chosen by get_provider() based on whether llama-cpp-python
is importable. If it is, we use it; otherwise we fall back to the mock so the
sidecar stays functional without the vlm extra installed.
"""

from __future__ import annotations

import asyncio
import os
import sys
from abc import ABC, abstractmethod
from typing import Callable, Optional

# Type alias for the cooperative cancellation callback. The batch manager
# passes a closure that reads its own `cancel_requested` flag; the provider
# polls it during inference and raises CaptionCancelled when it flips true.
CancelCheck = Callable[[], bool]


class CaptionCancelled(Exception):
    """Raised by a provider when inference is aborted via cancel_check."""


class CaptioningProvider(ABC):
    """Abstract base for captioning backends."""

    @abstractmethod
    async def caption_image(
        self,
        image_path: str,
        model_path: str,
        prompt: str,
        max_tokens: int = 512,
        temperature: float = 0.7,
        cancel_check: Optional[CancelCheck] = None,
    ) -> str:
        """Return a natural-language caption for the image."""

    @abstractmethod
    async def unload(self) -> None:
        """Release any cached model resources (GPU memory, etc.)."""


class MockCaptioningProvider(CaptioningProvider):
    """
    Mock provider that returns deterministic fake captions.

    Used to validate the end-to-end pipeline without needing a real VLM.
    Simulates ~300ms of inference per image so batch progress feels real.
    """

    def __init__(self) -> None:
        self._loaded_model: str | None = None

    async def caption_image(
        self,
        image_path: str,
        model_path: str,
        prompt: str,
        max_tokens: int = 512,
        temperature: float = 0.7,
        cancel_check: Optional[CancelCheck] = None,
    ) -> str:
        # Simulate model loading (first call only)
        if self._loaded_model != model_path:
            await asyncio.sleep(0.5)
            self._loaded_model = model_path

        # Simulate per-image inference latency, checking for cancellation
        for _ in range(3):
            if cancel_check and cancel_check():
                raise CaptionCancelled("cancelled during mock inference")
            await asyncio.sleep(0.1)

        filename = os.path.basename(image_path)
        return (
            f"A detailed descriptive caption for {filename}. "
            f"This is a mock response generated by the sidecar for testing. "
            f"Prompt was: {prompt[:80]}"
        )

    async def unload(self) -> None:
        self._loaded_model = None


# Module-level singleton — one provider instance per sidecar process
_provider: CaptioningProvider | None = None


def get_provider() -> CaptioningProvider:
    """
    Get the current captioning provider (lazily instantiated).

    Uses llama-cpp-python if available, otherwise falls back to the mock
    provider. This keeps the sidecar functional even without the vlm extra.
    """
    global _provider
    if _provider is not None:
        return _provider

    try:
        from captioning.llama_cpp_provider import LlamaCppCaptioningProvider

        _provider = LlamaCppCaptioningProvider()
        print("[sidecar] Captioning: using LlamaCppCaptioningProvider")
    except ImportError as err:
        print(
            f"[sidecar] Captioning: llama-cpp-python unavailable ({err}), "
            "falling back to mock provider",
            file=sys.stderr,
        )
        _provider = MockCaptioningProvider()

    return _provider


async def unload_provider() -> None:
    """Release the current provider's model resources."""
    global _provider
    if _provider is not None:
        await _provider.unload()
